Feature: First entry into a trusted flake directory
  As a developer using xi develop
  I want my devshell to activate automatically when I cd into a trusted flake
  So that I have the right tools available without manual setup

  Background:
    Given a parent shell with eval "$(xi develop activate zsh)" loaded
    And the xi binary is available at $__XI_BIN

  Scenario: First entry into a trusted flake with no daemon running
    Given a directory "~/projectA" containing a valid flake.nix
    And "~/projectA" is trusted via "xi develop trust"
    And no daemon is running for "~/projectA"
    When the user runs "cd ~/projectA"
    And the parent prompt hook fires
    And "xi develop prompt" runs with "--pid $PARENT_PID -s zsh"
    Then "xi develop prompt" walks up from CWD and finds flake.nix at "~/projectA"
    And "xi develop prompt" starts a daemon for "~/projectA"
    And "xi develop prompt" waits for the daemon socket to accept connections within 3 seconds
    And the daemon begins initial evaluation with state "Evaluating"
    And "xi develop prompt" outputs a subshell spawn command to stdout
    And the parent shell evals the output, spawning "subshell-A"

  Scenario: Subshell initialization sequence
    Given a subshell has been spawned for "~/projectA"
    Then the subshell init script generated by Rust performs these steps in order:
      | Step | Action                                                     |
      | 1    | Source user's shell rc (~/.zshrc via ZDOTDIR trick)        |
      | 2    | Install subshell prompt hook calling "xi develop prompt --subshell" |
      | 3    | Query daemon for env file path                             |
      | 4    | Source env-default.current.sh                              |
      | 5    | Source hook-default.current.sh                             |
      | 6    | Install EXIT trap calling "xi develop prompt --exit --pid $$" |
      | 7    | cd to original CWD (where user was before subshell)        |
    And the daemon registers the subshell PID as a consumer with shell_count=1

  Scenario: Initial build notification flow
    Given a subshell has been spawned and the daemon is evaluating
    When the user sees the first prompt inside the subshell
    Then stderr shows a loading notification "building devshell..."
    And the notification was retrieved from the daemon notification bus
    And when the evaluation completes successfully
    Then the next prompt stderr shows a success notification "devshell ready" with duration

  Scenario: Daemon is already running and healthy
    Given a directory "~/projectA" containing a valid flake.nix
    And "~/projectA" is trusted
    And a daemon is already running for "~/projectA" with matching version
    When the user runs "cd ~/projectA"
    And the parent prompt hook fires
    Then "xi develop prompt" connects to the existing daemon (does not start a new one)
    And a subshell is spawned as normal
    And the daemon registers the new consumer PID
