Feature: Uniform shell support (bash, zsh, fish)
  As a developer using any of bash, zsh, or fish
  I want the same devshell behavior regardless of shell
  So that there are no per-shell surprises or missing features

  Scenario: Activation stub is minimal and identical in structure
    When "xi develop activate bash" is called
    Then it outputs a minimal shell stub containing:
      | Element                    | Purpose                          |
      | __XI_BIN resolution        | Persist xi binary path           |
      | _xi_hook function          | Calls "xi develop prompt" on prompt |
      | Prompt hook installation   | PROMPT_COMMAND / precmd / fish_prompt |
    And the stub is less than 10 lines of shell code
    And the same structural pattern applies to zsh and fish

  Scenario: All shells use the subshell model
    Given any of bash, zsh, or fish
    When entering a trusted flake directory
    Then a subshell is spawned (same model for all shells)
    And exit = clean environment (subshell boundary)
    And no per-shell optimization or divergence

  Scenario: Subshell init per shell type
    Then subshell initialization uses shell-specific mechanisms:
      | Shell | Init method                               |
      | bash  | bash --rcfile /tmp/xi-init.bash            |
      | zsh   | ZDOTDIR=/tmp/xi-init-zsh/ zsh             |
      | fish  | fish --init-command "source /tmp/init.fish"|
    But the content of the init script is generated by the same Rust code
    And the init script always: sources user rc, sources env, sources hook, installs prompt hook, installs EXIT trap

  Scenario: Env file syntax matches shell
    Then env files are generated per shell syntax:
      | Shell     | Export syntax              | File extension |
      | bash/zsh  | export KEY='value'         | .sh            |
      | fish      | set -gx KEY 'value'        | .fish          |
    And the cleanup preamble uses shell-appropriate syntax
    And the injected vars registry uses shell-appropriate syntax

  Scenario: Shell type is passed explicitly, not detected
    When "xi develop prompt -s zsh --pid $$" runs
    Then the shell type comes from the "-s" flag
    And Rust generates output appropriate for that shell
    And there is no runtime shell detection or $SHELL sniffing in the prompt path
