[package]
name                   = "xi-darwin"
description            = "This is an internal component crate of xi"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
publish                = true

[lib]
path = "src/darwin.rs"

[dependencies]
clap.workspace          = true
clap_complete.workspace = true
color-eyre.workspace    = true
inquire.workspace    = true
xi-core.workspace    = true
xi-diff.workspace    = true
xi-remote.workspace  = true
nix.workspace        = true
tempfile.workspace   = true
tracing.workspace    = true

[lints]
workspace = true
