[package]
name                   = "xi-auth"
description            = "This is an internal component crate of xi"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
publish                = true

[dependencies]
clap.workspace       = true
color-eyre.workspace = true
tracing.workspace    = true
which.workspace      = true

[lints]
workspace = true
